name: Build Docs

on:
  workflow_call:
    inputs:
      runs-on-config:
        required: true
        type: string
      python-version:
        required: true
        type: string
      dotnet-sdk-version: # New input for .NET SDK version
        required: true
        type: string

jobs:
  build-docs:
    runs-on: ${{ inputs.runs-on-config }}
    name: Build Docs (.NET ${{ inputs.dotnet-sdk-version }}) # Updated name
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Setup .NET environment
      - name: Setup .NET ${{ inputs.dotnet-sdk-version }}
        uses: ./.github/actions/setup-dotnet
        with:
          dotnet-version: ${{ inputs.dotnet-sdk-version }} # Pass the input here

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
           
      # Generate API Reference Docs
      - name: Generate API Reference Docs
        shell: pwsh
        run: |
          ./scripts/generate-docs.ps1 -SkipPreClean

      # Upload Docs Artifact
      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./docs
