name: Deploy Docs

on:
  workflow_call:
    inputs:
      runs-on-config:
        required: true
        type: string
      publish-environment:
        description: "The github environment that has the variables and secrets"
        required: true
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish-docs:
    environment:
      name: ${{ inputs.publish-environment }}
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ${{ inputs.runs-on-config }}
    name: Publish docs
    steps:
      # Download Docs
      - name: Download Docs
        uses: actions/download-artifact@v4
        with:
          name: docs

      # Setup GitHub Pages
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5.0.0

      # Upload to GitHub Pages
      - name: Upload Github Pages
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "."

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
