# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .Net Publish Docs - Dry-Run

on:
  workflow_call:
    inputs:
      runs-on-config:
        required: true
        type: string
      build-config:
        required: true
        type: string
      python-version:
        required: true
        type: string

jobs:
  publish-docs:
    runs-on: ${{ inputs.runs-on-config }}
    name: Publish docs - Dry-Run
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-dotnet
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Generate API Reference Docs..
      shell: pwsh
      run: |
        ./scripts/generate-docs.ps1 -SkipPreClean
        Compress-Archive ./docs/* -Destination docs.zip 
    - name: Upload Docs Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: docs.zip