name: Test Python Workflow

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      test-name:
        required: true
        type: string
      dotnet-build-version:
        required: true
        type: string

env:
  DOTNET_NOLOGO: "true"
  MIG_SDK_PYTHON_BUILD: ${{ vars.MIG_SDK_PYTHON_BUILD }}

jobs:
  test-python:
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(vars.BUILD_OS) }}
        config: ${{ fromJSON(vars.BUILD_CONFIGURATIONS) }}
        dotnet-version: ['8.0.x', '9.0.x']

    runs-on: ${{ matrix.os }}
    name: Test Python ${{ inputs.test-name }} (${{ matrix.os }}, ${{ matrix.config }}, .NET ${{ matrix.dotnet-version }})
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Clean all existing .NET installations
      - name: Clean existing .NET installations
        uses: ./.github/actions/clean-dotnet

      # Setup .NET environment
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: ./.github/actions/setup-dotnet
        with:
          dotnet-version: ${{ matrix.dotnet-version }} # Pass the .NET version from the matrix

      # Restore Tools (i.e. report generator) - skip for .NET 8
      # Code coverage report generation is only supported on the latest .NET version
      - name: Restore .NET Tools
        if: ${{ !(matrix.dotnet-version == '8.0.x') }}
        run: dotnet tool restore

      # Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.PYTHON_TEST_VERSIONS }}
          cache: "pip" # caching pip dependencies

      # Cache Hatch environments
      - name: Cache Hatch environments
        uses: actions/cache@v4
        with:
          # Default Hatch env location relative to working-directory.
          path: ./.hatch
          # Key depends on OS and python version, plus project/dependency files
          key: ${{ runner.os }}-py${{ vars.PYTHON_TEST_VERSIONS }}-hatch-${{ hashFiles('./pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-py${{ vars.PYTHON_TEST_VERSIONS }}-hatch-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch

      # Download the published test artifacts
      # This step is only needed when builing the main python project, but it left in this
      # reuseable workflow for simplicity.
      # TODO: [W-18497981: CI/CD Improvements: Python tests should test final package | Work](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002EIUwKYAX/view)
      - uses: actions/download-artifact@v4
        with:
          name: tests-${{ matrix.config }}-net${{ inputs.dotnet-build-version }}
          path: ./src/Python/src/tableau_migration/bin/

      # Test with pytest
      - name: Test with pytest
        run: python -m hatch --data-dir=.hatch --cache-dir=.hatch_cache run test:testcov

      # Build code coverage reports
      - name: Build Coverage Summary
        if: ${{ !(matrix.dotnet-version == '8.0.x') }}
        run: dotnet reportgenerator -reports:"./TestResults/coverage*.xml" -targetdir:"./TestResults/coverage-reports" -reporttypes:"Html;MarkdownSummaryGithub"

      # Create job summary
      - name: Set Job Summary
        if: ${{ !(matrix.dotnet-version == '8.0.x') }}
        run: cat "./TestResults/coverage-reports/SummaryGithub.md" >> $GITHUB_STEP_SUMMARY
        shell: bash

      # Upload test results
      - name: Upload Test Results
        if: ${{ !(matrix.dotnet-version == '8.0.x') }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.test-name }}-results-${{ matrix.os }}-${{ matrix.config }}-net${{ matrix.dotnet-version }}
          path: ${{ inputs.working-directory }}/TestResults
          if-no-files-found: error
